<?php
/**
 * Properties for the miniShop snippet.
 *
 * @package minishop
 * @subpackage build
 */
$properties = array();

$properties[0] = array();
$properties[1] = array();
$properties[2] = array();
$properties[3] = array();
$properties[4] = array();

$properties[5] = array(
	array(
		'name' => 'action',
		'value' => 'getCart',
		'type' => 'list',
		'desc' => 'ms.action',
		'lexicon' => 'minishop:properties',
		'options' => array(
			array('text' => 'getCart','value' => 'getCart'),
			array('text' => 'getMiniCart','value' => 'getMiniCart'),
			array('text' => 'getDelivery','value' => 'getDelivery'),
			array('text' => 'getPayments','value' => 'getPayments'),
			array('text' => 'submitOrder','value' => 'submitOrder'),
			array('text' => 'getMyOrdersList','value' => 'getMyOrdersList'),
			array('text' => 'redirectCustomer','value' => 'redirectCustomer'),
			array('text' => 'receivePayment','value' => 'receivePayment'),
		),
	),
	array(
		'name' => 'tplCartOuter',
		'value' => 'tpl.msCart.outer',
		'type' => 'textfield',
		'desc' => 'ms.tplCartOuter',
		'lexicon' => 'minishop:properties',
		'options' => '',
	),
	array(
		'name' => 'tplCartRow',
		'value' => 'tpl.msCart.row',
		'type' => 'textfield',
		'desc' => 'ms.tplCartRow',
		'lexicon' => 'minishop:properties',
		'options' => '',
	),
	array(
		'name' => 'tplDeliveryRow',
		'value' => 'tpl.msDelivery.row',
		'type' => 'textfield',
		'desc' => 'ms.tplDeliveryRow',
		'lexicon' => 'minishop:properties',
		'options' => '',
	),
	array(
		'name' => 'tplPaymentRow',
		'value' => 'tpl.msPayment.row',
		'type' => 'textfield',
		'desc' => 'ms.tplPaymentRow',
		'lexicon' => 'minishop:properties',
		'options' => '',
	),
	array(
		'name' => 'tplAddrForm',
		'value' => 'tpl.msAddrForm',
		'type' => 'textfield',
		'desc' => 'ms.tplAddrForm',
		'lexicon' => 'minishop:properties',
		'options' => '',
	),
	array(
		'name' => 'tplOrderEmailUser',
		'value' => 'tpl.msOrderEmail.user',
		'type' => 'textfield',
		'desc' => 'ms.tplOrderEmailUser',
		'lexicon' => 'minishop:properties',
		'options' => '',
	),
	array(
		'name' => 'tplOrderEmailManager',
		'value' => 'tpl.msOrderEmail.manager',
		'type' => 'textfield',
		'desc' => 'ms.tplOrderEmailManager',
		'lexicon' => 'minishop:properties',
		'options' => '',
	),
	array(
		'name' => 'tplOrderEmailRow',
		'value' => 'tpl.msOrderEmail.row',
		'type' => 'textfield',
		'desc' => 'ms.tplOrderEmailRow',
		'lexicon' => 'minishop:properties',
		'options' => '',
	),
	array(
		'name' => 'tplSubmitOrderSuccess',
		'value' => 'tpl.msSubmitOrder.success',
		'type' => 'textfield',
		'desc' => 'ms.tplSubmitOrderSuccess',
		'lexicon' => 'minishop:properties',
		'options' => '',
	),
	array(
		'name' => 'tplMyOrdersList',
		'value' => 'tpl.msMyOrdersList',
		'type' => 'textfield',
		'desc' => 'ms.tplMyOrdersList',
		'lexicon' => 'minishop:properties',
		'options' => '',
	),
	array(
		'name' => 'tplPaymentForm',
		'value' => 'tpl.msPayment.form',
		'type' => 'textfield',
		'desc' => 'ms.tplPaymentForm',
		'lexicon' => 'minishop:properties',
		'options' => '',
	),
	array(
		'name' => 'tplMiniCart',
		'value' => 'tpl.msCart.mini',
		'type' => 'textfield',
		'desc' => 'ms.tplMiniCart',
		'lexicon' => 'minishop:properties',
		'options' => '',
	),
	array(
		'name' => 'debug',
		'value' => false,
		'type' => 'combo-boolean',
		'desc' => 'ms.debug',
		'lexicon' => 'minishop:properties',
		'options' => '',
	),
	array(
		'name' => 'userGroups',
		'value' => '',
		'type' => 'textfield',
		'desc' => 'ms.userGroups',
		'lexicon' => 'minishop:properties',
		'options' => '',
	)
);

$properties[6] = array();
$properties[7] = array(
	array(
		'name' => 'tpl',
		'desc' => 'gr.tpl',
		'type' => 'textfield',
		'options' => '',
		'value' => '',
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'tplOdd',
		'desc' => 'gr.tplOdd',
		'type' => 'textfield',
		'options' => '',
		'value' => '',
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'tplFirst',
		'desc' => 'gr.tplFirst',
		'type' => 'textfield',
		'options' => '',
		'value' => '',
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'tplLast',
		'desc' => 'gr.tplLast',
		'type' => 'textfield',
		'options' => '',
		'value' => '',
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'sortby',
		'desc' => 'gr.sortby',
		'type' => 'textfield',
		'options' => '',
		'value' => 'publishedon',
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'sortbyTV',
		'desc' => 'Name of a Template Variable to sort by. Defaults to empty string.',
		'type' => 'textfield',
		'options' => '',
		'value' => '',
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'sortbyTVType',
		'desc' => 'gr.sortbyTVType',
		'type' => 'list',
		'options' => array(
			array('text' => 'string', 'value' => 'string'),
			array('text' => 'integer', 'value' => 'integer'),
			array('text' => 'decimal', 'value' => 'decimal'),
			array('text' => 'datetime', 'value' => 'datetime'),
		),
		'value' => 'string',
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'sortbyAlias',
		'desc' => 'gr.sortbyAlias',
		'type' => 'textfield',
		'options' => '',
		'value' => '',
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'sortbyEscaped',
		'desc' => 'gr.sortbyEscaped',
		'type' => 'textfield',
		'options' => '',
		'value' => '0',
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'sortdir',
		'desc' => 'gr.sortdir',
		'type' => 'list',
		'options' => array(
			array('text' => 'ASC','value' => 'ASC'),
			array('text' => 'DESC','value' => 'DESC'),
		),
		'value' => 'DESC',
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'sortdirTV',
		'desc' => 'gr.sortdirTV',
		'type' => 'list',
		'options' => array(
			array('text' => 'ASC','value' => 'ASC'),
			array('text' => 'DESC','value' => 'DESC'),
		),
		'value' => 'DESC',
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'limit',
		'desc' => 'gr.limit',
		'type' => 'textfield',
		'options' => '',
		'value' => '5',
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'offset',
		'desc' => 'gr.offset',
		'type' => 'textfield',
		'options' => '',
		'value' => '0',
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'tvFilters',
		'desc' => 'gr.tvFilters',
		'type' => 'textfield',
		'options' => '',
		'value' => '',
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'depth',
		'desc' => 'gr.depth',
		'type' => 'textfield',
		'options' => '',
		'value' => '10',
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'parents',
		'desc' => 'gr.parents',
		'type' => 'textfield',
		'options' => '',
		'value' => '',
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'includeContent',
		'desc' => 'gr.includeContent',
		'type' => 'combo-boolean',
		'options' => '',
		'value' => false,
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'includeTVs',
		'desc' => 'gr.includeTVs',
		'type' => 'combo-boolean',
		'options' => '',
		'value' => false,
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'includeTVList',
		'desc' => 'gr.includeTVList',
		'type' => 'textfield',
		'options' => '',
		'value' => '',
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'showHidden',
		'desc' => 'gr.showHidden',
		'type' => 'combo-boolean',
		'options' => '',
		'value' => false,
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'showUnpublished',
		'desc' => 'gr.showUnpublished',
		'type' => 'combo-boolean',
		'options' => '',
		'value' => false,
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'showDeleted',
		'desc' => 'gr.showDeleted',
		'type' => 'combo-boolean',
		'options' => '',
		'value' => false,
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'resources',
		'desc' => 'gr.resources',
		'type' => 'textfield',
		'options' => '',
		'value' => '',
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'processTVs',
		'desc' => 'gr.processTVs',
		'type' => 'combo-boolean',
		'options' => '',
		'value' => false,
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'processTVList',
		'desc' => 'gr.processTVList',
		'type' => 'textfield',
		'options' => '',
		'value' => '',
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'tvPrefix',
		'desc' => 'gr.tvPrefix',
		'type' => 'textfield',
		'options' => '',
		'value' => 'tv.',
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'idx',
		'desc' => 'gr.idx',
		'type' => 'textfield',
		'options' => '',
		'value' => '',
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'first',
		'desc' => 'gr.first',
		'type' => 'textfield',
		'options' => '',
		'value' => '',
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'last',
		'desc' => 'gr.last',
		'type' => 'textfield',
		'options' => '',
		'value' => '',
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'toPlaceholder',
		'desc' => 'gr.toPlaceholder',
		'type' => 'textfield',
		'options' => '',
		'value' => '',
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'toSeparatePlaceholders',
		'desc' => 'gr.toSeparatePlaceholders',
		'type' => 'textfield',
		'options' => '',
		'value' => '',
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'debug',
		'desc' => 'gr.debug',
		'type' => 'combo-boolean',
		'options' => '',
		'value' => false,
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'where',
		'desc' => 'gr.where',
		'type' => 'textfield',
		'options' => '',
		'value' => '',
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'dbCacheFlag',
		'desc' => 'gr.dbCacheFlag',
		'type' => 'textfield',
		'options' => '',
		'value' => '0',
		'lexicon' => 'minishop:properties',
	),
	array(
		'name' => 'context',
		'desc' => 'gr.context',
		'type' => 'textfield',
		'options' => '',
		'value' => '',
		'lexicon' => 'minishop:properties',
	),

	array(
		'name' => 'sortbyMS',
		'desc' => 'gr.sortbyMS',
		'type' => 'textfield',
		'options' => '',
		'value' => '',
		'lexicon' => 'minishop:properties',
	)
);
$properties[8] = array();

$properties[9] = array(
	array(
		'name' => 'id',
		'value' => 0,
		'type' => 'numberfield',
		'desc' => 'ms.id',
		'lexicon' => 'minishop:properties',
		'options' => '',
	),
	array(
		'name' => 'tpl',
		'value' => 'tpl.msGallery.row',
		'type' => 'textfield',
		'desc' => 'ms.tpl',
		'lexicon' => 'minishop:properties',
		'options' => '',
	),
	array(
		'name' => 'limit',
		'value' => 10,
		'type' => 'numberfield',
		'desc' => 'ms.limit',
		'lexicon' => 'minishop:properties',
		'options' => '',
	),
	array(
		'name' => 'offset',
		'value' => 0,
		'type' => 'numberfield',
		'desc' => 'ms.offset',
		'lexicon' => 'minishop:properties',
		'options' => '',
	),
	array(
		'name' => 'outputSeparator',
		'value' => "\n",
		'type' => 'textfield',
		'desc' => 'ms.outputSeparator',
		'lexicon' => 'minishop:properties',
		'options' => '',
	),
	array(
		'name' => 'totalVar',
		'value' => 'total',
		'type' => 'textfield',
		'desc' => 'ms.totalVar',
		'lexicon' => 'minishop:properties',
		'options' => '',
	),
	array(
		'name' => 'sortby',
		'value' => 'id',
		'type' => 'textfield',
		'desc' => 'ms.sortby',
		'lexicon' => 'minishop:properties',
		'options' => '',
	),
	array(
		'name' => 'sortdir',
		'value' => 'ASC',
		'type' => 'list',
		'desc' => 'ms.sortdir',
		'lexicon' => 'minishop:properties',
        'options' => array(
            array('text' => 'ASC','value' => 'ASC'),
            array('text' => 'DESC','value' => 'DESC'),
        ),
	),
	array(
		'name' => 'onlyImg',
		'value' => true,
		'type' => 'combo-boolean',
		'desc' => 'ms.onlyImg',
		'lexicon' => 'minishop:properties',
		'options' => '',
	),
);

return $properties;
?>